[package]
name = "crochet"
version = "0.1.0"
authors = ["Raph Levien <raph.levien@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.druid]
git = "https://github.com/linebender/druid"
rev = "7c3646509fffb412d16f5746b8a6c11dbaacd602"

[dependencies]
log = "0.4.11"
